
/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.36                          *
*        Compiled Aug 31 2016, 10:53:09                              *
*        (c) 2016 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Emwin_eric800.h"
#include "InitSystem.h"
//#include	"GUI.h"
		
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x0)
#define ID_BUTTON_0     (GUI_ID_USER + 0x1)
#define ID_BUTTON_1     (GUI_ID_USER + 0x2)
#define ID_TEXT_0 	    (GUI_ID_USER + 0x03)
#define ID_TEXT_1 	    (GUI_ID_USER + 0x04)
#define ID_TEXT_2 	    (GUI_ID_USER + 0x05)


#define WM_SetValue 		WM_USER + 0x01 /* ????? */ // -------------- (2)

uint8_t FaultStyleSel;

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogmessegeCreate[] = {
  { WINDOW_CreateIndirect, "NumPad", ID_WINDOW_0, 200, 200, 400, 180, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 40, 117, 120, 46, 0, 0x0, 0},
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 240, 117, 120, 46, 0, 0x0, 0},
  { TEXT_CreateIndirect, "", ID_TEXT_0, 32, 0, 368, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_1, 32, 32, 368, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_2, 32, 64, 368, 32, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};


/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static void DisplayMessge(WM_MESSAGE * pMsg)
{
	WM_HWIN hItem;
	uint8_t i;
	char s[512],PhaseNum;
	for(i=0;i<FaultSaveSIZE;i++){
		if(FaultFifo[i]->DislayFlag & 0x04){
			FaultFifo[i]->DislayFlag &= ~0x04;
			break;
		}
	}
	if(i<FaultSaveSIZE){
		
		switch(FaultFifo[i]->FaultStyle){
			case GroundFault:
				FaultStyleSel = GroundFault;
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				sprintf(s,"%d/%d/%d %d:%d:%d %3dms",
							  FaultFifo[i]->Tim.year,FaultFifo[i]->Tim.month,FaultFifo[i]->Tim.day,
								FaultFifo[i]->Tim.hour,FaultFifo[i]->Tim.minute,FaultFifo[i]->Tim.second,
								FaultFifo[i]->Tim.us/1000);
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				
				if(FaultFifo[i]->ValueFlag & 0x01){
					PhaseNum = 'A';
				}else if(FaultFifo[i]->ValueFlag & 0x02){
					PhaseNum = 'B';
				}else{
					PhaseNum = 'C';
				}
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				
				GA_WavePosition=0;// add by seleen 2021 09/01
				//sprintf(s,"%c相%d路发生接地故障!",PhaseNum,FaultSelFifo[i]->FaultFlag+1);
				
		  	if(0 == FaultAllSelFifo[i]->CanId[0]){					
					sprintf(s,"%c相%d路发生接地故障!",PhaseNum,FaultAllSelFifo[i]->FaultFlag[0]+1);
				}else{
					sprintf(s,"%c相CanID:%d发生接地故障!",PhaseNum,FaultAllSelFifo[i]->CanId[0]);
				}
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
					
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				sprintf(s,"详情请点击>>");				
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				break;
			case SysExceedValueFault:
				FaultStyleSel = SysExceedValueFault;
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				sprintf(s,"%d/%d/%d %d:%d:%d %3dms",
							  FaultFifo[i]->Tim.year,FaultFifo[i]->Tim.month,FaultFifo[i]->Tim.day,
								FaultFifo[i]->Tim.hour,FaultFifo[i]->Tim.minute,FaultFifo[i]->Tim.second,
								FaultFifo[i]->Tim.us/1000);
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				switch(FaultFifo[i]->ValueFlag & 0x07){
					case 0x01:
						sprintf(s,"A相发生系统过电压");
						break;
					case 0x02:
						sprintf(s,"B相发生系统过电压");
						break;
					case 0x04:
						sprintf(s,"C相发生系统过电压");
						break;
					case 0x03:
						sprintf(s,"AB相发生系统过电压");
						break;
					case 0x05:
						sprintf(s,"AC相发生系统过电压");
						break;
					case 0x06:
						sprintf(s,"BC相发生系统过电压");
						break;					
				}
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
					
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				sprintf(s,"详情请点击>>");				
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				break;
			case ExceedValueFault:
				FaultStyleSel = ExceedValueFault;
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				sprintf(s,"%d/%d/%d %d:%d:%d %3dms",
							  FaultFifo[i]->Tim.year,FaultFifo[i]->Tim.month,FaultFifo[i]->Tim.day,
								FaultFifo[i]->Tim.hour,FaultFifo[i]->Tim.minute,FaultFifo[i]->Tim.second,
								FaultFifo[i]->Tim.us/1000);
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				switch(FaultFifo[i]->ValueFlag & 0x07){
					case 0x01:
						sprintf(s,"A相发生过电压");
						break;
					case 0x02:
						sprintf(s,"B相发生过电压");
						break;
					case 0x04:
						sprintf(s,"C相发生过电压");
						break;
					case 0x03:
						sprintf(s,"AB相发生过电压");
						break;
					case 0x05:
						sprintf(s,"AC相发生过电压");
						break;
					case 0x06:
						sprintf(s,"BC相发生过电压");
						break;					
				}
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				sprintf(s,"详情请点击>>");				
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				break;
			case PTFault:
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				sprintf(s,"%d/%d/%d %d:%d:%d %3dms",
							  FaultFifo[i]->Tim.year,FaultFifo[i]->Tim.month,FaultFifo[i]->Tim.day,
								FaultFifo[i]->Tim.hour,FaultFifo[i]->Tim.minute,FaultFifo[i]->Tim.second,
								FaultFifo[i]->Tim.us/1000);
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
			
				if(FaultFifo[i]->ValueFlag & 0x80){					
					FaultStyleSel = LowValueFault;
				}else{				
					FaultStyleSel = PTFault;
				}
				
				switch(FaultFifo[i]->ValueFlag & 0x07){
					case 0x01:
						if(FaultFifo[i]->ValueFlag & 0x80){
							sprintf(s,"A相发生欠压");
						}else{
							sprintf(s,"A相发生PT断线");
						}
						break;
					case 0x02:
						if(FaultFifo[i]->ValueFlag & 0x80){
							sprintf(s,"B相发生欠压");	
							
						}else{
							sprintf(s,"B相发生PT断线");							
						}
						break;
					case 0x04:
						if(FaultFifo[i]->ValueFlag & 0x80){
							sprintf(s,"C相发生欠压");							
						}else{
							sprintf(s,"C相发生PT断线");							
						}
						break;
					case 0x03:
						if(FaultFifo[i]->ValueFlag & 0x80){
							sprintf(s,"AB相发生欠压");							
						}else{
							sprintf(s,"AB相发生PT断线");							
						}
						break;
					case 0x05:
						if(FaultFifo[i]->ValueFlag & 0x80){
							sprintf(s,"AC相发生欠压");							
						}else{
							sprintf(s,"AC相发生PT断线");							
						}
						break;
					case 0x06:
						if(FaultFifo[i]->ValueFlag & 0x80){
							sprintf(s,"BC相发生欠压");							
						}else{
							sprintf(s,"BC相发生PT断线");							
						}
						break;					
				}
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				sprintf(s,"详情请点击>>");				
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				break;
			case ShortFault:
				FaultStyleSel = ShortFault;
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				sprintf(s,"%d/%d/%d %d:%d:%d %3dms",
							  FaultFifo[i]->Tim.year,FaultFifo[i]->Tim.month,FaultFifo[i]->Tim.day,
								FaultFifo[i]->Tim.hour,FaultFifo[i]->Tim.minute,FaultFifo[i]->Tim.second,
								FaultFifo[i]->Tim.us/1000);
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);				
				sprintf(s,"发生短路故障");					
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
				TEXT_SetBkColor(hItem,GUI_WHITE);
				TEXT_SetTextColor(hItem, GUI_RED);
				sprintf(s,"详情请点击>>");				
				TEXT_SetFont(hItem, &XBF_Font32);	
				TEXT_SetText(hItem,s);
				break;
		}
		

	}	
}//DisplayMessge
// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialogmessege(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  //GUI_RECT r;
  //unsigned i;
  int     NCode;
  int     Id;
  BUTTON_SKINFLEX_PROPS BUTTON_Props;
  
  //int	Pressed;
  //WM_HWIN hDlg;
  
  //Pressed=0;
  //hDlg=pMsg->hWin;
  
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_TIMER:
	WM_RestartTimer(pMsg->Data.v,1000);
	
	DisplayMessge(pMsg);
	break;
  case WM_PAINT:
  	//WM_GetClientRect(&r);
  	//GUI_SetColor(0x000000);
  	//GUI_DrawRect(r.x0, r.y0, r.x1, r.y1); /* Draw rectangle around it */ /* Draw the bright sides */ 
  	//GUI_SetColor(0xffffff); 
  	//GUI_DrawHLine(r.y0 + 1,r.x0+1,r.x1 - 2); /* Draw top line */
  	//GUI_DrawVLine(r.x0 + 1,r.y0+1,r.y1 - 2); /* Draw the dark sides */ 
  	//GUI_SetColor(0x555555); 
  	//GUI_DrawHLine(r.y1 -1, r.x0+1,r.x1 - 1); 
  	//GUI_DrawVLine(r.x1 -1, r.y0+1,r.y1 - 2); 
  	break;	
  	
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Button'
		
    GUI_SendKeyMsg(GUI_KEY_TAB, 1);
	GUI_SendKeyMsg(GUI_KEY_BACKTAB, 1);
	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	//BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED,GUI_WHITE);
	//BUTTON_SetBkColor(hItem,BUTTON_CI_PRESSED,GUI_RED);
	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_RED);
	BUTTON_SetTextColor(hItem,BUTTON_CI_PRESSED,GUI_WHITE);
	BUTTON_SetFont(hItem,&XBF_Font32);	
    BUTTON_SetText(hItem, "确定");	
    BUTTON_SetFocussable(hItem,0);

	/* 获取按钮启动状态的皮肤 */
    BUTTON_GetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_ENABLED); //--------------（ 2）
    BUTTON_Props.aColorFrame[0] = GUI_RED; //--------------（ 3）
    BUTTON_Props.aColorFrame[1] = GUI_WHITE;
    BUTTON_Props.aColorFrame[2] = GUI_WHITE;
	BUTTON_Props.aColorLower[0] = GUI_WHITE;
    BUTTON_Props.aColorLower[1] = GUI_WHITE;
    BUTTON_Props.aColorUpper[0] = GUI_WHITE;
    BUTTON_Props.aColorUpper[1] = GUI_WHITE;
    
    /* 设置按下启动状态的皮肤色 */
    BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_ENABLED); //--------------（ 4）

    /* 设置聚焦状态的皮肤色 */
    BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_FOCUSSED); //--------------（ 5）

    BUTTON_Props.aColorFrame[0] = GUI_RED;
    BUTTON_Props.aColorFrame[1] = GUI_RED;
    BUTTON_Props.aColorFrame[2] = GUI_RED;
    BUTTON_Props.aColorLower[0] = GUI_RED;
    BUTTON_Props.aColorLower[1] = GUI_RED;
    BUTTON_Props.aColorUpper[0] = GUI_RED;
    BUTTON_Props.aColorUpper[1] = GUI_RED;
    /* 设置按下状态的皮肤色 */
    BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_PRESSED);

	
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	//BUTTON_SetBkColor(hItem,BUTTON_CI_UNPRESSED,GUI_WHITE);
	//BUTTON_SetBkColor(hItem,BUTTON_CI_PRESSED,GUI_RED);
	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_RED);
	BUTTON_SetTextColor(hItem,BUTTON_CI_PRESSED,GUI_WHITE);
	BUTTON_SetFont(hItem,&XBF_Font32);
    BUTTON_SetText(hItem, "取消");	
    BUTTON_SetFocussable(hItem,0);
	
	/* 获取按钮启动状态的皮肤 */
    BUTTON_GetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_ENABLED); //--------------（ 2）
    BUTTON_Props.aColorFrame[0] = GUI_RED; //--------------（ 3）
    BUTTON_Props.aColorFrame[1] = GUI_WHITE;
    BUTTON_Props.aColorFrame[2] = GUI_WHITE;
	BUTTON_Props.aColorLower[0] = GUI_WHITE;
    BUTTON_Props.aColorLower[1] = GUI_WHITE;
    BUTTON_Props.aColorUpper[0] = GUI_WHITE;
    BUTTON_Props.aColorUpper[1] = GUI_WHITE;
    
    /* 设置按下启动状态的皮肤色 */
    BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_ENABLED); //--------------（ 4）

    /* 设置聚焦状态的皮肤色 */
    BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_FOCUSSED); //--------------（ 5）

    BUTTON_Props.aColorFrame[0] = GUI_RED;
    BUTTON_Props.aColorFrame[1] = GUI_RED;
    BUTTON_Props.aColorFrame[2] = GUI_RED;
    BUTTON_Props.aColorLower[0] = GUI_RED;
    BUTTON_Props.aColorLower[1] = GUI_RED;
    BUTTON_Props.aColorUpper[0] = GUI_RED;
    BUTTON_Props.aColorUpper[1] = GUI_RED;
    /* 设置按下状态的皮肤色 */
    BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_PRESSED);
		
    //hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	//TEXT_SetBkColor(hItem,GUI_WHITE);
	//TEXT_SetTextColor(hItem, GUI_RED);
	//sprintf(s," 2019/09/09 00:00:00\r\n XX相xx路发生接地故障！\r\n 详情请点击>>");
	//TEXT_SetFont(hItem, &XBF_Font32);	
	//TEXT_SetText(hItem,s);
    
    DisplayMessge(pMsg);
    // USER END
    break;
	case WM_PRE_PAINT:		
		break;
				
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
  
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
		MessgeFlag = Messge_SkipWave;
		SelectGndWave = 4;
		GUI_EndDialog(pMsg->hWin,0);
		//CreateMain();
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
			
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
		MessgeFlag = Messge_idle;
		GUI_EndDialog(pMsg->hWin,0);
		//CreateMain();
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    }
    break;
  
    
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateNumPad
*/

WM_HWIN CreateMain_messge(void);
WM_HWIN CreateMain_messge(void){
    WM_HWIN hWin;
	WM_HTIMER hTimer;	

	hWin = GUI_CreateDialogBox(_aDialogmessegeCreate, GUI_COUNTOF(_aDialogmessegeCreate), _cbDialogmessege, WM_HBKWIN, 0, 0);

	
	hTimer =WM_CreateTimer(WM_GetClientWindow(hWin),0,500,0);
	(void)hTimer;
	
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/





// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
