/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.36                          *
*        Compiled Aug 31 2016, 10:53:09                              *
*        (c) 2016 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Emwin_eric800.h"
#include "InitSystem.h"
#include "NumPadDLG.h"
#include "param.h"
extern const unsigned char _aclogo2_s[17237UL + 1];





/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0      (GUI_ID_USER + 0x00)
#define ID_BUTTON_0      (GUI_ID_USER + 0x01)
#define ID_BUTTON_1      (GUI_ID_USER + 0x02)
#define ID_BUTTON_2      (GUI_ID_USER + 0x03)
#define ID_BUTTON_3      (GUI_ID_USER + 0x04)
#define ID_BUTTON_4      (GUI_ID_USER + 0x05)
#define ID_BUTTON_5      (GUI_ID_USER + 0x06)
#define ID_BUTTON_6      (GUI_ID_USER + 0x07)
#define ID_BUTTON_7      (GUI_ID_USER + 0x08)
#define ID_BUTTON_8      (GUI_ID_USER + 0x09)
#define ID_BUTTON_9      (GUI_ID_USER + 0x0A)
#define ID_BUTTON_10      (GUI_ID_USER + 0x0B)
#define ID_BUTTON_11      (GUI_ID_USER + 0x0C)
#define ID_BUTTON_20      (GUI_ID_USER + 0x0D)
#define ID_BUTTON_30      (GUI_ID_USER + 0x0E)
#ifdef EnableSyntonySet
#define ID_BUTTON_31      (GUI_ID_USER + 0x0F)
#endif
#define ID_BUTTON_12      (GUI_ID_USER + 0x10)
#define ID_TEXT_0      (GUI_ID_USER + 0x11)
#define ID_BUTTON_13      (GUI_ID_USER + 0x12)
#define ID_TEXT_1      (GUI_ID_USER + 0x13)
#define ID_BUTTON_14      (GUI_ID_USER + 0x14)
#define ID_BUTTON_15      (GUI_ID_USER + 0x15)
#define ID_BUTTON_16      (GUI_ID_USER + 0x16)
#define ID_BUTTON_17      (GUI_ID_USER + 0x17)
#define ID_TEXT_2      (GUI_ID_USER + 0x18)
#define ID_TEXT_3      (GUI_ID_USER + 0x19)
#define ID_TEXT_4      (GUI_ID_USER + 0x20)
#define ID_TEXT_5      (GUI_ID_USER + 0x21)
#define ID_BUTTON_25   (GUI_ID_USER + 0x22)
#define ID_BUTTON_26   (GUI_ID_USER + 0x23)
#define ID_TEXT_6      (GUI_ID_USER + 0x24)

#define ID_BUTTON_27   (GUI_ID_USER + 0x25)
#define ID_BUTTON_28   (GUI_ID_USER + 0x26)
#define ID_TEXT_7      (GUI_ID_USER + 0x27)



// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "OutPutTest_S", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "RealMonitor", ID_BUTTON_0, 150, 0, 129, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SystemSet", ID_BUTTON_1, 280, 0, 129, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "AlarmList", ID_BUTTON_2, 410, 0, 129, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "PowerQuality", ID_BUTTON_3, 540, 0, 129, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "About us", ID_BUTTON_4, 670, 0, 129, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Temp&Humdity Set", ID_BUTTON_5, 0, 75, 150, 43, 0, 0x0, 0},
  { BUTTON_CreateIndirect, "Communication Set", ID_BUTTON_6, 0, 120, 150, 43, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Cupboard Set", ID_BUTTON_7, 0, 165, 150, 43, 0, 0x0, 0},
  { BUTTON_CreateIndirect, "PT&CT Set", ID_BUTTON_8, 0, 210, 150, 43, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Leakage Current Set", ID_BUTTON_9, 0, 255, 150, 43, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Voltag Limit Set", ID_BUTTON_10, 0, 300, 150, 43, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OutPut Set", ID_BUTTON_11, 0, 345, 150, 43, 0, 0x0, 0},
	{ BUTTON_CreateIndirect, "Calibration Set", ID_BUTTON_20, 0, 390, 150, 43, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Calibration Set", ID_BUTTON_30,  0, 435, 150, 43, 0, 0x0, 0 },
	#ifdef EnableSyntonySet
	{ BUTTON_CreateIndirect, "Syntony Set", ID_BUTTON_31, 0, 425, 150, 39, 0, 0x0, 0 },
	#endif
  { BUTTON_CreateIndirect, "A_On", ID_BUTTON_12, 210, 110, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "A Phase", ID_TEXT_0, 220, 80, 80, 30, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "A_Off", ID_BUTTON_13, 210, 160, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "B Phase", ID_TEXT_1, 360, 80, 80, 30, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "B_On", ID_BUTTON_14, 350, 110, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "B_Off", ID_BUTTON_15, 350, 160, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "C_On", ID_BUTTON_16, 490, 110, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "C_Off", ID_BUTTON_17, 490, 160, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "C Phase", ID_TEXT_2, 500, 80, 80, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "OnoffStatus", ID_TEXT_3, 210, 240, 160, 30, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "OnStatus", ID_TEXT_4, 170, 290, 50, 30, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "OffStatus", ID_TEXT_5, 170, 350, 50, 30, 0, 0x64, 0 },
	{ BUTTON_CreateIndirect, "", ID_BUTTON_25, 620, 80, 40, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_26, 660, 80, 40, 30, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "TestStatus", ID_TEXT_6, 710, 80, 50, 30, 0, 0x64, 0 },
	{ BUTTON_CreateIndirect, "", ID_BUTTON_27, 620, 135, 40, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_28, 660, 135, 40, 30, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "DistanceStatus", ID_TEXT_7, 710, 135, 50, 30, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

static void _cbButton0(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("RealMonitor", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font32);
			GUI_DispStringInRect("实时监控", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton1(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
		/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("SystemSet", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font32);
			GUI_DispStringInRect("系统设置", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton2(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}

			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("AlarmList", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font32);
			GUI_DispStringInRect("告警查询", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton3(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}

			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("PowerQuality", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font32);
			GUI_DispStringInRect("电能质量", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton4(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}

			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("About us", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font32);
			GUI_DispStringInRect("关于我们", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton5(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}

			/*
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringInRect("Temp&Humdity Set", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font24);
			GUI_DispStringInRect("参数设置", &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton6(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}

			/*
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringInRect("Communication Set", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font24);
			GUI_DispStringInRect("通讯设置", &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton7(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}

			/*
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringInRect("Cupboard Set", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font24);
			GUI_DispStringInRect("柜体设置", &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton8(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}

			/*
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringInRect("PT&CT Set", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font24);
			GUI_DispStringInRect("PT&CT设置", &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton9(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}
		/*
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringInRect("Leakage Current Set", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font24);
			//GUI_DispStringInRect("漏电流设置", &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			GUI_DispStringInRect("零序电流设置", &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton10(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringInRect("Voltage Limit Set", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font24);
			GUI_DispStringInRect("电压门限设置", &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton11(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringInRect("Voltage Limit Set", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font24);
			GUI_DispStringInRect("传动实验", &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton20(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringInRect("Voltage Limit Set", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font24);
			GUI_DispStringInRect("校准设置", &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton30(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringInRect("Voltage Limit Set", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font24);
			GUI_DispStringInRect("通用设置", &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}
#ifdef EnableSyntonySet
static void _cbButton31(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringInRect("Voltage Limit Set", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			GUI_SetFont(&XBF_Font24);
			GUI_DispStringInRect("谐振设置", &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}
#endif
static void _cbButton25(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("About us", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			//GUI_SetFont(&XBF_Font32);
			//GUI_DispStringInRect("閸忓厖绨幋鎴滄粦", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}
static void _cbButton25B(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("About us", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			//GUI_SetFont(&XBF_Font32);
			//GUI_DispStringInRect("閸忓厖绨幋鎴滄粦", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}


static void _cbButton26(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("About us", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			//GUI_SetFont(&XBF_Font32);
			//GUI_DispStringInRect("閸忓厖绨幋鎴滄粦", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}



static void _cbButton26B(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("About us", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			//GUI_SetFont(&XBF_Font32);
			//GUI_DispStringInRect("閸忓厖绨幋鎴滄粦", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

static void _cbButton27(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("About us", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			//GUI_SetFont(&XBF_Font32);
			//GUI_DispStringInRect("閸忓厖绨幋鎴滄粦", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}
static void _cbButton27B(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("About us", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			//GUI_SetFont(&XBF_Font32);
			//GUI_DispStringInRect("閸忓厖绨幋鎴滄粦", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}


static void _cbButton28(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("About us", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			//GUI_SetFont(&XBF_Font32);
			//GUI_DispStringInRect("閸忓厖绨幋鎴滄粦", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}



static void _cbButton28B(WM_MESSAGE * pMsg)
{
	WM_HWIN  hWin;
	GUI_RECT Rect;
	hWin  = pMsg->hWin;

	switch (pMsg->MsgId)
	{
		case WM_PAINT:
			WM_GetClientRect(&Rect);
			if (BUTTON_IsPressed(hWin))
			{
				GUI_SetColor(0x000455ea);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x000455ea);
				GUI_SetColor(GUI_WHITE);
			}
			else
			{
				GUI_SetColor(0x00959595);
				GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
				GUI_SetBkColor(0x00959595);
				GUI_SetColor(GUI_WHITE);
			}
			/*
			GUI_SetFont(&GUI_Font20_ASCII);
			GUI_DispStringInRect("About us", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			*/
			//GUI_SetFont(&XBF_Font32);
			//GUI_DispStringInRect("閸忓厖绨幋鎴滄粦", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			break;

		default:
			BUTTON_Callback(pMsg);
	}
}

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
	WM_HWIN hWinOld;
  int     NCode;
  int     Id;
	GUI_MEMDEV_Handle hMemJPEG;
  GUI_JPEG_INFO JpegInfo;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
		case WM_TIMER:
			WM_RestartTimer(pMsg->Data.v,1000);
		
		//===========
	
		
		hWinOld= WM_SelectWindow(WM_GetClientWindow(pMsg->hWin));

		//====A 相合闸开闸指示
		if(SystemState.SwitchState.phaseAction&0x01)
		GUI_SetColor(GUI_RED);
		else
		GUI_SetColor(GUI_GRAY);
		//GUI_SetColor(GUI_YELLOW);
		GUI_FillCircle(250,300,25);
		
		if(SystemState.SwitchState.phaseAction&0x01)
		GUI_SetColor(GUI_GRAY);
		else
		GUI_SetColor(GUI_GREEN);
		//GUI_SetColor(GUI_YELLOW);
		GUI_FillCircle(250,360,25);
		
		//====B 相合闸开闸指示
		if(SystemState.SwitchState.phaseAction&0x02)
		GUI_SetColor(GUI_RED);
		else
		GUI_SetColor(GUI_GRAY);
		//GUI_SetColor(GUI_YELLOW);
		GUI_FillCircle(390,300,25);
		
		if(SystemState.SwitchState.phaseAction&0x02)
		GUI_SetColor(GUI_GRAY);
		else
		GUI_SetColor(GUI_GREEN);
		//GUI_SetColor(GUI_YELLOW);
		GUI_FillCircle(390,360,25);
		
		//====C 相合闸开闸指示
		if(SystemState.SwitchState.phaseAction&0x04)
		GUI_SetColor(GUI_RED);
		else
		GUI_SetColor(GUI_GRAY);
		//GUI_SetColor(GUI_YELLOW);
		GUI_FillCircle(530,300,25);
		
		
		if(SystemState.SwitchState.phaseAction&0x04)
		GUI_SetColor(GUI_GRAY);
		else
		GUI_SetColor(GUI_GREEN);
		//GUI_SetColor(GUI_YELLOW);
		GUI_FillCircle(530,360,25);
		
	 
		WM_SelectWindow(hWinOld);
   
		break;
		
	 case WM_PAINT:
      //========bmp logo
    GUI_JPEG_GetInfo(_aclogo2_s, sizeof(_aclogo2_s) ,&JpegInfo);

    hMemJPEG = GUI_MEMDEV_CreateEx(2,2,JpegInfo.XSize,JpegInfo.YSize,GUI_MEMDEV_NOTRANS);
    //hMemJPEG = GUI_MEMDEV_CreateFixed(0,0,JpegInfo.XSize,JpegInfo.YSize,GUI_MEMDEV_HASTRANS,GUI_MEMDEV_APILIST_16,GUICC_M565 );
    GUI_MEMDEV_Select(hMemJPEG);
    GUI_JPEG_Draw(_aclogo2_s,sizeof(_aclogo2_s),0,0);
    GUI_MEMDEV_Select(0);

    GUI_MEMDEV_WriteAt(hMemJPEG,2,2);
	 
	  GUI_MEMDEV_Delete(hMemJPEG);//

	 
	 
	 



      break;	
		
  case WM_INIT_DIALOG:
    //
    // Initialization of 'OutPutTest_S'
    //
    
		hItem = pMsg->hWin;
    FRAMEWIN_SetTitleVis(hItem, 0);
    FRAMEWIN_SetClientColor(hItem,0x00333333);
    //
    // Initialization of 'A_On'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
   // BUTTON_SetText(hItem, "ON");
		 BUTTON_SetText(hItem, "合闸");
    //BUTTON_SetFont(hItem, GUI_FONT_20_1);
		 BUTTON_SetFont(hItem, &XBF_Font24);
    //
    // Initialization of 'A Phase'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    //TEXT_SetFont(hItem, GUI_FONT_20_1);
		TEXT_SetFont(hItem,&XBF_Font24 );
   // TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
	  
    TEXT_SetText(hItem, "A 相");
    //
    // Initialization of 'A_Off'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
    BUTTON_SetText(hItem, "分闸");
    BUTTON_SetFont(hItem,&XBF_Font24 );
    //
    // Initialization of 'B Phase'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &XBF_Font24);
    //TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
    TEXT_SetText(hItem, "B 相");
    //
    // Initialization of 'B_On'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
    BUTTON_SetText(hItem, "合闸");
    BUTTON_SetFont(hItem, &XBF_Font24);
    //
    // Initialization of 'B_Off'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
    BUTTON_SetText(hItem, "分闸");
    BUTTON_SetFont(hItem, &XBF_Font24);
    //
    // Initialization of 'C_On'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
    BUTTON_SetFont(hItem, &XBF_Font24);
    BUTTON_SetText(hItem, "合闸");
    //
    // Initialization of 'C_Off'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_17);
    BUTTON_SetFont(hItem, &XBF_Font24);
    BUTTON_SetText(hItem, "分闸");
    //
    // Initialization of 'C Phase'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &XBF_Font24);
   // TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
    TEXT_SetText(hItem, "C 相");
    //
    // Initialization of 'OnoffStatus'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem, "合闸分闸状态");
    TEXT_SetFont(hItem, &XBF_Font24);
    //TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000FF00));
		
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "合闸");
    TEXT_SetFont(hItem, &XBF_Font24);
    //TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000FF00));
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetText(hItem, "分闸");
    TEXT_SetFont(hItem, &XBF_Font24);
    //TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000FF00));
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetText(hItem, "开启");
    TEXT_SetFont(hItem, &XBF_Font24);
    TEXT_SetTextColor(hItem, GUI_GREEN);
		
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
		        //回调函数BUTTON换肤
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton0);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton1);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton2);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton3);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton4);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton5);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton6);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton7);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton8);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton9);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton10);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton11);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_20);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton20);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_30);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton30);
		#ifdef EnableSyntonySet
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_31);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton31);
		#endif
		if(Setting.DriveTestFlag==1)
		{	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_25);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton25);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_26);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton26B);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetText(hItem, "开启");
    TEXT_SetFont(hItem, &XBF_Font24);
    TEXT_SetTextColor(hItem, GUI_GREEN);
		}
		else
		{
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_25);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton25B);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_26);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton26);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetText(hItem, "中断");
    TEXT_SetFont(hItem, &XBF_Font24);
    //TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
		}
		
		if(Setting.DistanceFlag==1)
		{	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_27);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton27);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_28);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton28B);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetText(hItem, "远方");
    TEXT_SetFont(hItem, &XBF_Font24);
    TEXT_SetTextColor(hItem, GUI_GREEN);
		}
		else
		{
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_27);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton27B);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_28);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cbButton28);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetText(hItem, "就地");
    TEXT_SetFont(hItem, &XBF_Font24);
   // TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
		}
		if(NumPadOpen==1)
				{
					GUI_EndDialog(NM_hWin,0);
					NumPadOpen=0;
				}
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'RealMonitor'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        CreateMain();//切换到主画面
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'SystemSet'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'AlarmList'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        CreateOverVoltage_A();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'PowerQuality'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
				CreatePowerQuality();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'About us'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        Createaboutus();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Temp&Humdity Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        CreateTempHumdity_S();//切换到系统设置画面
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Communication Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        CreateCommunication_s();//
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'Cupboard Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        CreateCupboard_S();//
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'PT&CT Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        CreatePTCT_S();//
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'Leakage Current Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        CreateLeakageCurrent_S();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'Voltag Limit Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        CreateVoltageLimit_S();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'OutPut Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
		case ID_BUTTON_20: // Notifications sent by 'Voltag Limit Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        
				Calibration_S();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;

		case ID_BUTTON_30: // Notifications sent by 'Device Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        
				CreateDevice_S();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
		#ifdef EnableSyntonySet	
		case ID_BUTTON_31: // Notifications sent by 'Device Set'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(pMsg->hWin,0);
        
				CreateSyntony();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;	
			#endif
    case ID_BUTTON_12: // Notifications sent by 'A_On'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(0 != PutOP_LED_STATE()) //投运不处理
				break;	
				SystemState.SwitchState.AphaseState=1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_13: // Notifications sent by 'A_Off'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(0 != PutOP_LED_STATE()) //投运不处理
				break;
				SystemState.SwitchState.AphaseState=2;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_14: // Notifications sent by 'B_On'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(0 != PutOP_LED_STATE()) //投运不处理
				break;
				SystemState.SwitchState.BphaseState=1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_15: // Notifications sent by 'B_Off'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(0 != PutOP_LED_STATE()) //投运不处理
				break;
				SystemState.SwitchState.BphaseState=2;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_16: // Notifications sent by 'C_On'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(0 != PutOP_LED_STATE()) //投运不处理
				break;
				SystemState.SwitchState.CphaseState=1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_17: // Notifications sent by 'C_Off'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			if(0 != PutOP_LED_STATE()) //投运不处理
				break;
				SystemState.SwitchState.CphaseState=2;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			
			case ID_BUTTON_25: // OutputTest use
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_25);
				WM_SetHasTrans(hItem);
				WM_SetCallback(hItem, _cbButton25);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_26);
				WM_SetHasTrans(hItem);
				WM_SetCallback(hItem, _cbButton26B);
			
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
				TEXT_SetText(hItem, "开启");
				TEXT_SetFont(hItem, &XBF_Font24);
				TEXT_SetTextColor(hItem, GUI_GREEN);
				Setting.DriveTestFlag=1;
				//g_tParam.DriveTestFlag=1;
				//SaveParam();
				SystemSet.ParamSaveFlag = FlagSystemState;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			
			case ID_BUTTON_26: // OutputTest not use
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_25);
				WM_SetHasTrans(hItem);
				WM_SetCallback(hItem, _cbButton25B);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_26);
				WM_SetHasTrans(hItem);
				WM_SetCallback(hItem, _cbButton26);
			
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
				TEXT_SetText(hItem, "中断");
				TEXT_SetFont(hItem, &XBF_Font24);
				//TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
				Setting.DriveTestFlag=0;
				//g_tParam.DriveTestFlag=0;
				//SaveParam();
				SystemSet.ParamSaveFlag = FlagSystemState;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			
			case ID_BUTTON_27: // OutputTest use
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_27);
				WM_SetHasTrans(hItem);
				WM_SetCallback(hItem, _cbButton27);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_28);
				WM_SetHasTrans(hItem);
				WM_SetCallback(hItem, _cbButton28B);
			
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
				TEXT_SetText(hItem, "远方");
				TEXT_SetFont(hItem, &XBF_Font24);
				TEXT_SetTextColor(hItem, GUI_GREEN);
				Setting.DistanceFlag=1;
				//g_tParam.DistanceFlag=1;
				//SaveParam();
				SystemSet.ParamSaveFlag = FlagSystemState;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			
			case ID_BUTTON_28: // OutputTest not use
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_27);
				WM_SetHasTrans(hItem);
				WM_SetCallback(hItem, _cbButton27B);
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_28);
				WM_SetHasTrans(hItem);
				WM_SetCallback(hItem, _cbButton28);
			
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
				TEXT_SetText(hItem, "就地");
				TEXT_SetFont(hItem, &XBF_Font24);
				//TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000080FF));
				Setting.DistanceFlag=0;
				//g_tParam.DistanceFlag=0;
				//SaveParam();
				SystemSet.ParamSaveFlag = FlagSystemState;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;			
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateOutPutTest_S
*/
WM_HWIN CreateOutPutTest_S(void);
WM_HWIN CreateOutPutTest_S(void) {
  WM_HWIN hWin;
	WM_HTIMER hTimer;

  //hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	hTimer =WM_CreateTimer(WM_GetClientWindow(hWin),0,100,0);
	(void)hTimer;
  return hWin;
	
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
