/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.36                          *
*        Compiled Aug 31 2016, 10:53:09                              *
*        (c) 2016 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Emwin_eric800.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0  (GUI_ID_USER + 0x00)
#define ID_BUTTON_0  (GUI_ID_USER + 0x01)
#define ID_BUTTON_1  (GUI_ID_USER + 0x02)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Calibration", ID_FRAMEWIN_0, 0, 2, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Start", ID_BUTTON_0, 160, 160, 125, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Calibration", ID_BUTTON_1, 160, 260, 125, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  BUTTON_SKINFLEX_PROPS BUTTON_Props; //
  FRAMEWIN_SKINFLEX_PROPS FRAMEWIN_Props;
 // BUTTON_Handle hButton;

  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {

  case WM_PAINT:
        GUI_SetColor(GUI_BLACK);
        GUI_SetTextMode(GUI_TM_TRANS);
        //GUI_SetFont(GUI_FONT_20_1);
				GUI_SetFont(&XBF_Font24);
        //GUI_DispStringAt("Calibration Current&Voltage ", 108, 104);
				GUI_DispStringAt("校准电压电流 ", 108, 104);
        //GUI_DispStringAt("Voltage 100V,Current 5A ", 326, 183);
				GUI_DispStringAt("电压 100V,电流 5A ", 326, 183);
      break;
  case WM_INIT_DIALOG:


    //
    // Initialization of 'Calibration'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleVis(hItem, 0);
    GUI_Clear();

    FRAMEWIN_SetClientColor(hItem,GUI_WHITE);

    //====================
    FRAMEWIN_GetSkinFlexProps(&FRAMEWIN_Props,FRAMEWIN_SKINFLEX_PI_INACTIVE);
    FRAMEWIN_Props.BorderSizeL=0;
    FRAMEWIN_Props.BorderSizeR=0;
    FRAMEWIN_Props.BorderSizeT=0;
    FRAMEWIN_Props.BorderSizeB=0;
    FRAMEWIN_Props.aColorFrame[0]=GUI_WHITE;
    FRAMEWIN_Props.aColorFrame[1]=GUI_WHITE;
    FRAMEWIN_Props.aColorFrame[2]=GUI_WHITE;
    FRAMEWIN_Props.Radius=0;
    FRAMEWIN_Props.SpaceX=0;
    FRAMEWIN_Props.aColorTitle[0]=GUI_WHITE;
    FRAMEWIN_Props.aColorTitle[1]=GUI_WHITE;
    FRAMEWIN_SetSkinFlexProps(&FRAMEWIN_Props,FRAMEWIN_SKINFLEX_PI_INACTIVE);

    FRAMEWIN_GetSkinFlexProps(&FRAMEWIN_Props,FRAMEWIN_SKINFLEX_PI_ACTIVE);
    FRAMEWIN_Props.BorderSizeL=0;
    FRAMEWIN_Props.BorderSizeR=0;
    FRAMEWIN_Props.BorderSizeT=0;
    FRAMEWIN_Props.BorderSizeB=0;
    FRAMEWIN_Props.aColorFrame[0]=GUI_WHITE;
    FRAMEWIN_Props.aColorFrame[1]=GUI_WHITE;
    FRAMEWIN_Props.aColorFrame[2]=GUI_WHITE;
    FRAMEWIN_Props.Radius=0;
    FRAMEWIN_Props.SpaceX=0;
    FRAMEWIN_Props.aColorTitle[0]=GUI_WHITE;
    FRAMEWIN_Props.aColorTitle[1]=GUI_WHITE;
    FRAMEWIN_SetSkinFlexProps(&FRAMEWIN_Props,FRAMEWIN_SKINFLEX_PI_ACTIVE);



    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0);

    BUTTON_GetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_ENABLED);

    BUTTON_Props.aColorFrame[0]=0x0084b4f6;
    BUTTON_Props.aColorFrame[1]=0x0084b4f6;
    BUTTON_Props.aColorFrame[2]=0x00f2f4fe;

    BUTTON_Props.aColorUpper[0]=0x00f2f4fe;
    BUTTON_Props.aColorUpper[1]=0x00f2f4fe;

    BUTTON_Props.aColorLower[0]=0x00f2f4fe;
    BUTTON_Props.aColorLower[1]=0x00f2f4fe;

    BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_ENABLED);
    BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_FOCUSSED);

    BUTTON_Props.aColorFrame[0]=0x0084b4f6;
    BUTTON_Props.aColorFrame[1]=GUI_GREEN;
    BUTTON_Props.aColorFrame[2]=GUI_GREEN;

    BUTTON_Props.aColorUpper[0]=GUI_GREEN;
    BUTTON_Props.aColorUpper[1]=GUI_GREEN;

    BUTTON_Props.aColorLower[0]=GUI_GREEN;
    BUTTON_Props.aColorLower[1]=GUI_GREEN;
    BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_PRESSED);//设置按下皮肤
		
		hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0);
		BUTTON_SetFont(hItem,&XBF_Font24);
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,0x000455ea);
		BUTTON_SetText(hItem,"准备");
		
		hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1);
		BUTTON_SetFont(hItem,&XBF_Font24);
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,0x000455ea);
		BUTTON_SetText(hItem,"校准");
		





    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Start'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Calibration'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
         GUI_EndDialog(pMsg->hWin,0);
         CreateMain();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateCalibration
*/
WM_HWIN CreateCalibration(void);
WM_HWIN CreateCalibration(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
